# Generated by Django 2.1 on 2023-01-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20230128_0714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='addresses',
            unique_together=set(),
        ),
    ]
